---
title: "Mondovisioni 2020-2021 - le anteprime dei documentari"
date: 2020-10-08
categories: ["FiorDaFiore"]
tags: ["documentari", "hong kong moments", "internazionale", "mondovisioni", "oeconomia", "reunited", "the fever", "we hold the line"]
---

![](mondovisioni.jpg)
](https://missotter.wordpress.com/wp-content/uploads/2020/10/mondovisioni.jpg)

Lo scorso fine settimana al festival di Internazionale a Ferrara ho visto cinque dei sei documentari presentati in anteprima nazionale all’interno della rassegna Mondovisioni, edizione 2020-2021. Dopo l’anteprima, la rassegna è partita per il tour nelle sale cinematografiche italiane, i film sono in proiezione in questi giorni a Roma, al Palazzo delle esposizioni e a Lugo di Romagna, il seguito della programmazione lo troverete via via aggiornato in [questa pagina](https://www.cineagenzia.it/progetti/mondovisioni-i-documentari-di-internazionale-2020-2021/).

La rassegna di quest’anno si presenta in tono minore, sia per le restrizioni imposte dalle norme anti-Covid, sia per il numero di documentari ridotto a sei, rispetto ai consueti otto. Le proposte, grazie all’attenta selezione di Cineagenzia, sono comunque sempre molto interessanti.

Il documentario più entusiasmante e coinvolgente a mio parere è *[We Hold the Line](https://www.cineagenzia.it/film/we-hold-the-line/)*, del regista tedesco Marc Wiese, che racconta la battaglia della giornalista [Maria Ressa](https://twitter.com/mariaressa) e della sua testata online, Rappler, contro gli abusi del dittatore filippino Rodrigo Duterte. Il film ha un ritmo incalzante, è arricchito da testimonianze che fanno accapponare la pelle, fra cui quelle dello stesso presidente Duterte e di alcuni dei componenti delle sue squadre della morte, e dipinge con affetto la figura granitica e straordinariamente coraggiosa di Maria Ressa che, a rischio della sua stessa vita, mantiene una fiducia incrollabile nelle istituzioni democratiche e nella libertà di stampa in un paese in cui entrambe sono messe a durissima prova.

Il cinese Zhou Bing, documentarista di grande esperienza, impressiona con *[Hong Kong Moments](https://www.cineagenzia.it/film/hong-kong-moments/),* la sua opera dedicata alla citta di Hong Kong e ai suoi abitanti. La scelta di prospettiva è molto chiara: le telecamere seguono, con un approccio di totale neutralità, sette cittadini molto diversi fra loro (un manifestante in prima linea, un paramedico soccorritore, un tassista, la proprietaria di una tea house, un poliziotto delle squadre antisommossa e due candidati alle elezioni amministrative dello scorso novembre) durante alcune delle giornate più intense degli ultimi due anni, da quando la discussa legge sull’estradizione ha ridato vigore alle proteste. Il film non spiega le origini e l’evoluzione dell’Umbrella Movement né aiuta a comprendere la posta in gioco per il destino di Hong Kong, ma catapulta lo spettatore nel bel mezzo dei fatti, grazie a panoramiche mozzafiato della città dall’alto e immagini riprese dalle squadre di Zhou nel vivo delle proteste (i più attenti vi riconosceranno [il momento](https://www.nytimes.com/2019/10/01/world/asia/hong-kong-protestor-shot.html) in cui, il 1 ottobre scorso, durante le manifestazioni in occasione del 70° anniversario della fondazione della Repubblica popolare cinese, la polizia ha sparato ad altezza uomo con proiettili veri uccidendo un manifestante). La città vibra e pulsa mentre le telecamere seguono i sette protagonisti alle prese con la loro vita quotidiana, senza che nessun giudizio venga formulato sulle loro opinioni o sul divario generazionale che le caratterizza, ogni valutazione è lasciata allo spettatore.

Originale e accattivante è anche il documentario *[Oeconomia](https://www.cineagenzia.it/film/oeconomia/)*, di un’altra tedesca, Carmen Losmann. Visivamente affascinante quando ritrae l’algida architettura dei bellissimi e impenetrabili edifici della finanza mondiale, il film esplora le regole e le strutture del sistema economico capitalista, seguendo una logica ferrea nello svolgimento della sua tesi. Le numerose interviste, telefoniche o in presenza, sono intervallate da una grafica molto semplice che tiene il filo di un discorso complesso e riporta al sodo ogni divagazione. La regista pone ai suoi interlocutori delle domande apparentemente molto elementari ma si scontra di continuo con una difficoltà: gli intervistati sono talmente immersi nella complessità del contesto in cui operano da non riuscire a comprendere le domande o, quando le comprendono, da non essere in grado di formulare delle risposte semplici. Fa da contrappunto alle interviste, come un coro greco, una specie di gioco di ruolo interpretato da attori seduti attorno a un tavolo da ufficio nel bel mezzo di una piazza cittadina. Le loro interazioni e riflessioni ci aiutano a comprendere la verità ultima a cui approda il documentario: il sistema finanziario non è altro che un gioco a somma zero che per perpetuarsi richiede un costante incremento di capitali, perseguito a ogni costo.

*[Reunited](https://www.cineagenzia.it/film/reunited/)* prosegue la serie di documentari che la rassegna dedica da anni alle storie di migranti (menzione speciale per quello dello scorso anno, *[Midnight traveler](https://www.cineagenzia.it/film/midnight-traveler/)*, il meraviglioso e poetico racconto autobiografico del regista afghano Hassan Fazili) e simboleggia un po’ la fine di questo lungo viaggio perché documenta le traversie affrontate da una famiglia di siriani benestanti originari di Aleppo che, arrivata quasi alla meta, si trova smembrata e invischiata in un inestricabile groviglio burocratico: la madre è in Danimarca, il padre in Canada e i due figli, ancora minorenni, sono rimasti da soli in Turchia. Ci vorranno anni perché la famiglia possa riunirsi. Il documentario racconta, seguendo in presa diretta i quattro membri della famiglia nei luoghi in cui si trovano, il calvario dei molti tentativi fatti per sconfiggere una burocrazia ottusa e ritrovarsi finalmente riuniti. Il film è forse un po’ lento nel suo progredire, ma compensa con grande autenticità, sensibilità e compassione. La regista danese Mira Jargil ha dichiarato in [un’intervista](https://womenandhollywood.com/human-rights-watch-film-fest-2020-women-directors-meet-mira-jargil-reunited/) che il suo interesse è rivolto a quelle persone che affrontano cambiamenti e momenti decisivi nella propria vita o che sono alle prese con scelte difficili e situazioni complicate; non poteva scegliere soggetto più appropriato.

L’ultimo film che ho visto è *[The Fever](https://www.cineagenzia.it/film/the-fever/)*, dell’austriaca Katharina Weingartner, ed è quello che mi ha convinta di meno. Il tema del documentario è l’epidemia di malaria che affligge il continente africano, e ha una contiguità tematica, che personalmente ho trovato flebile, con la pandemia che stiamo attraversando. Il collegamento non è tanto con i metodi di prevenzione o le dinamiche di diffusione di un’epidemia (la modalità di trasmissione della malaria è peraltro totalmente diversa da quella del Covid-19) quanto con i metodi di cura. Il documentario segue il lavoro di [alcune persone](http://www.thefevermovie.com/) che, fra Kenya e Uganda, studiano e promuovono metodi non farmacologici di prevenzione e cura della malaria tramite la coltivazione e l’uso di una pianta, l’artemisia, il cui principio attivo, l’artemisinina, è alla base di diversi farmaci antimalarici. Se è vero che la somministrazione di decotti della pianta potrebbe contribuire a prevenire la malattia, quello che gli studi dell’OMS contestano è che i dosaggi non precisi o troppo bassi del principio attivo nei rimedi casalinghi rischiano di favorire la resistenza allo stesso del plasmodio, il parassita che causa la malaria. Il dubbio sollevato, ovvero che le multinazionali farmaceutiche facciano pressioni sull’OMS, sulla pelle degli africani, perché scoraggi l’uso di rimedi autoprodotti a scapito dei farmaci da loro commercializzati, non è poi così peregrino, ma gli argomenti portati dai protagonisti del documentario mi sono sembrati un po’ deboli.