---
title: "In nave verso l’Antartide (e ritorno) per studiare un ghiacciaio"
date: 2024-01-16
categories: ["NuoviArrivi"]
tags: ["anna crawford", "antartide", "baia di amundsen", "carolyn beeler", "donne in antartide", "Elizabeth Rush", "geofisica", "geologia", "GHC", "ghiacciaio", "International Thwaites glacier collaboration", "jeff goodell", "livello del mare", "nathaniel b palmer", "oceanografia", "pulitzer", "punta arenas", "rising", "rompighiaccio", "shackleton", "st. andrews university", "TARSAN", "terra del fuoco", "the quickening", "THOR", "thwaites"]
---

![](copertina.jpg)

Inizio l’anno con una nuova proposta dalle mie letture recenti. È ancora un resoconto di viaggio, ma molto diverso dal precedente: siamo su un nave rompighiaccio che, partita da Punta Arenas, nella Terra del Fuoco cilena, solca l’oceano in direzione della baia di Amundsen, in Antartide, dove si fermerà al cospetto di un ghiacciaio colossale. Ma partiamo dall’inizio.

Elizabeth Rush è una giornalista americana.

Il suo primo libro, *[Rising*](https://milkweed.org/book/rising), uscito nel 2018, è stato fra i finalisti del premio Pulitzer nel 2019 nella categoria "General Nonfiction". L’opera, mescolando reportage investigativo, narrazione personale e riflessioni etiche, esplora le conseguenze umane e ambientali dell'innalzamento del livello del mare per le comunità costiere degli Stati Uniti.

Il secondo libro di Elizabeth, uscito il 28 settembre scorso, si intitola *[The Quickening: Creation and Community at the Ends of the Earth](https://milkweed.org/book/the-quickening)* ed è pubblicato, come il precedente, da Milkweed Editions. Il “quickening” del titolo è un riferimento suggestivo a quello che sta succedendo al Thwaites, un ghiacciaio antartico grande come l’intero Regno Unito e con il fronte più ampio del mondo: 120 chilometri. Il ghiacciaio si sta assottigliando rapidamente e la velocità con cui avanza verso l’oceano ha accelerato in maniera allarmante. Fra gennaio e marzo del 2019, un consorzio scientifico internazionale ha condotto una spedizione per monitorare la velocità di avanzamento del ghiacciaio e recuperare una mole enorme di altri dati relativi a ghiaccio, terra, acqua e aria nell’area, e Rush è stata invitata a partecipare alla spedizione. Questo libro è il resoconto della sua esperienza a bordo della [rompighiaccio Nathaniel B. Palmer](https://en.wikipedia.org/wiki/Nathaniel_B._Palmer_(icebreaker)), intervallata a interviste ai membri della spedizione e alle sue riflessioni sul desiderio di maternità e su che cosa comporta mettere al mondo un figlio oggi.

La mia valutazione non è del tutto positiva: il libro ha dei difetti, fra poco ve ne parlerò, ma penso che valga la pena di proporvelo comunque perché parecchi sono gli aspetti positivi e interessanti.

La prima parte del libro ospita il resoconto della navigazione verso la baia di Amundsen, durante la quale l'autrice si concentra sulle persone a bordo della Palmer e sulle dinamiche che si creano in una circostanza tanto particolare. Dovete immaginare una nave – quindi un contesto già di per sé abbastanza claustrofobico – in viaggio per settimane in mezzo al nulla e, da un certo punto in poi, priva di ogni collegamento con il resto del mondo (niente telefono, Internet o televisione). Dimenticate le navi da crociera, progettate per intrattenere i passeggeri: la Palmer è un mezzo spartano, privo di molti comfort e anche della possibilità di procurarsi cibo fresco e variato. Per giunta, i passeggeri della nave compongono una comunità ristretta, con gradi molto vari di conoscenza reciproca e diversi livelli di esperienza di spedizioni antartiche, costretta per settimane a una quasi totale inattività, che si ingegna per combattere la noia, mantenere la salute mentale e la forma fisica e trarre un minimo di varietà alimentare dalle scorte presenti in cambusa. Senza dimenticare, naturalmente, la tensione e la trepidazione che aleggiano sull’impresa: molti degli esperimenti e dei rilevamenti che gli scienziati dovranno effettuare saranno unici, talvolta irripetibili, ed eseguibili soltanto in una finestra temporale molto ristretta e solo se le condizioni meteorologiche lo permettono.

Sulla nave ci sono cinquantasette persone, metà delle quali sono membri dell’equipaggio: capitano, marinai, cuochi, tecnici e ingegneri. L’altra metà è composta da scienziati e ricercatori, divisi in tre gruppi: il GHC e il THOR, composti in gran parte da geologi e geofisici marini, hanno l’obiettivo di ricostruire, analizzando i dati geologici ricavati dai sedimenti del fondale marino, il comportamento della massa di ghiaccio nel corso degli ultimi ventimila anni e di monitorare le variazioni storiche del livello del mare nell’area; il TARSAN, un gruppo composto per lo più da oceanografi, si propone di studiare le attuali interazioni fra l’oceano e la massa di ghiaccio e ha il compito ambizioso di inviare, per la prima volta nella storia, un veicolo autonomo sottomarino sotto la lingua del ghiacciaio che si protende nell’oceano. Il frutto del lavoro delle tre squadre offrirà un contributo fondamentale alla comprensione del comportamento attuale e futuro del Thwaites e di altri ghiacciai, permettendoci di prevedere con maggiore precisione la natura e la misura dei futuri innalzamenti del livello del mare.

La prima parte del libro, pervasa dal senso di aspettativa e immersa nelle atmosfere ovattate della nave in viaggio, è a mio giudizio la meglio riuscita e la più accattivante. Proprio l’aspettativa creata in questa prima parte, però, non viene soddisfatta appieno nella seconda. Quando si arriva al dunque e le squadre di ricercatori entrano in azione, Rush rimane concentrata sulle dinamiche umane e ci rende solo superficialmente partecipi del lavoro di cui è testimone. Questa mancanza a mio parere indebolisce un po’ un libro che, per la prima metà abbondante, aveva un ottimo potenziale.

Un altro aspetto molto interessante, che mi fa rimpiangere il fatto che il libro, da un certo punto in poi, si sciolga come il ghiacciaio di cui parla, è che storicamente – e lo sottolinea anche l’autrice – le esplorazioni dell’Antartide e il loro racconto sono stati quasi totalmente dominati da voci maschili (anche quando si è trattato di imprese fallimentari come quella, celeberrima, di Shackleton) e avere una prospettiva femminile sull’Antartide, ora che delle spedizioni scientifiche fanno parte molte più donne, potrebbe colmare qualche lacuna, oltre a mettere in luce problemi a lungo sottovalutati o ignorati, come le aggressioni sessuali denunciate in [questo articolo ](https://apnews.com/article/women-working-antarctica-sexual-harassment-assault-mcmurdo-ba0e550fddf1ab0afd031ff4d25143cb?mc_cid=80ee48b933&mc_eid=dd611e4753)pubblicato su APNews.

*            *            *

Ormai sapete che mi piace regalare qualche contenuto extra in chiusura dei miei post. È tutto tranne che una fatica per me, perché quando mi immergo in un libro è difficile che non mi venga voglia di approfondire qualche aspetto curiosando in rete, e da lì a cadere nella tana del bianconiglio e perderci ore… il passo è molto, molto breve!

Dato che Rush non è stata l’unica giornalista a partecipare alla spedizione, sono andata a dare un'occhiata ai lavori dei suoi colleghi: Carolyn Beeler ha prodotto dei [reportage interattivi per PRX](https://theworld.org/categories/thaw-decoding-thwaites-glacier) e Jeff Goodell un [diario di viaggio per Audible](https://www.audible.com/pd/The-Big-Melt-Audiobook/B07XVR866B) e una [serie di articoli per Rolling Stone](https://www.rollingstone.com/t/journey-to-antarctica/).

Per compensare la carenza di informazioni scientifiche nel libro, vi propongo [questo video di Youtube](https://youtu.be/KcxpyfVWYFE?si=KqYgZFEHo2w58HVd). Si tratta di una miniconferenza di Anna Crawford, ricercatrice dell'Università di St. Andrews e membro dell'International Thwaites Glacier Collaboration, il consorzio scientifico che ha dato vita alla spedizione. Crawford spiega bene la natura e lo scopo delle ricerche sul ghiacciaio Thwaites.

Tornando invece agli aspetti umani della spedizione: per chi, leggendo il libro, non saprà resistere alla tentazione di dare un volto ai suoi protagonisti, in [questa pagina](https://thwaitesglacier.org/people) è possibile cercare i nomi dei partecipanti e scoprire che aspetto hanno.